### ISSUE TITLE
Crashes on injecting

### ISSUE THREAD

**Issue by polybiusproxy** [pozm/godot_key_extract#1]
Hello there,

I am trying to get a game's encryption key, and I am having trouble with it.
Using your tool will crash the game, with no output.

After some debugging, I have discovered that it crashes on the `auto version_somewhere = ScanInternal((char*)version_sig, (char*)version_sig_mask, (char*)pog1, 0xfffffff)` line, with an access violation error.

The Godot version used on the game is `3.4.5.stable`.

Thanks.

**Comment by char-ptr** [comment]
That's really odd, would you be able to send me a sample (game) or a link to a sample? in the meantime i'll try to reproduce.

**Comment by char-ptr** [comment]
Hi, 
So i think i've figured it out, could you try using the new version from either building or downloading the dll from the [release page](https://github.com/pozm/godot_key_extract/releases/tag/1.0.1)

Please let me know if that's fixed your issue. 
If it doesn't i suspect something to do with mono version maybe? i haven't tested with mono (and not sure if you can enable encryption on it)

**Comment by polybiusproxy** [comment]
> Hi, So i think i've figured it out, could you try using the new version from either building or downloading the dll from the [release page](https://github.com/pozm/godot_key_extract/releases/tag/1.0.1)
> 
> Please let me know if that's fixed your issue. If it doesn't i suspect something to do with mono version maybe? i haven't tested with mono (and not sure if you can enable encryption on it)

Will do, thank you!
Do you have any e-mail so I can send you the sample?

**Comment by polybiusproxy** [comment]
Hello, @pozm

The issue is still occuring (`0xC0000005: Access violation reading location 0x0000000000000022`),
at line 60 (`std::memcpy(&act_offset, (void*)(offset + 3), 4)`), on function `find_rel_addr_lea`.

The problem appears to be on line 79 (`auto version_somewhere = ScanInternal((char*)version_sig, (char*)version_sig_mask, (char*)pog1, 0xfffffff)`), **where the ScanInternal function is returning NULL**.

You can e-mail me at daniel@polyproxy.xyz and I'll gladly provide you a sample. 🙂 

Thank you.

**Comment by char-ptr** [comment]
I'm sorry that the fix didn't work for you, when trying to reproduce i guess i found another bug with 3.4.5, and i have fixed that, but in regards to the memory access violation that is strange, as i managed to find the correct version of the game with the 3.4.5 engine. If i'm able to get a sample i'll see what's going on with it.

I have also sent you an email, so if you could check that it would be greatly appreciated. If you wanted to try to manually find the encryption you also could as i believe the README in this repository provides a good enough explanation of how to find the key via ida or some other static analysis program.

Thanks again,
luna

**Comment by polybiusproxy** [comment]
> I'm sorry that the fix didn't work for you, when trying to reproduce i guess i found another bug with 3.4.5, and i have fixed that, but in regards to the memory access violation that is strange, as i managed to find the correct version of the game with the 3.4.5 engine. If i'm able to get a sample i'll see what's going on with it.
> 
> I have also sent you an email, so if you could check that it would be greatly appreciated. If you wanted to try to manually find the encryption you also could as i believe the README in this repository provides a good enough explanation of how to find the key via ida or some other static analysis program.
> 
> Thanks again, luna

Hey there!

Removing the version detection code removed the crash and provided a 32bit hex key.
I don't have a way to confirm it's the actual key, but it worked nonetheless.

My e-mail provider has a very strict spam filter, so I may not received (I still haven't received your e-mail).

I tried to follow the instructions on README using IDA Pro, 
but I couldn't find the function.

Cheers!

**Comment by char-ptr** [comment]
That's strange that you were unable to find the function via the steps, but if the code managed to find it without the version detection that means that you can just search for it in ida via byte sequence. 

Ida byte sequence takes in a IDA pattern, so you will need to seperate the hex bytes with spaces and then for the entries which have a ? in the mask replace with ??, it should generally look like this `48 8D 05 ?? ?? ?? ?? 0F B6 0C 03` (you can probably try scanning for this but i'm unsure if you used <344 version). 

If you want, you can send me an email laixeria@gmail.com. I would still appreciate the sample so i can find out what is causing this to break and promptly patch it.

Thanks

**Comment by polybiusproxy** [comment]
> That's strange that you were unable to find the function via the steps, but if the code managed to find it without the version detection that means that you can just search for it in ida via byte sequence.
>
> Ida byte sequence takes in a IDA pattern, so you will need to seperate the hex bytes with spaces and then for the entries which have a ? in the mask replace with ??, it should generally look like this 48 8D 05 ?? ?? ?? ?? 0F B6 0C 03 (you can probably try scanning for this but i'm unsure if you used <344 version).
>
> If you want, you can send me an email [laixeria@gmail.com](mailto:laixeria@gmail.com). I would still appreciate the sample so i can find out what is causing this to break and promptly patch it.
>
> Thanks

Will e-mail you the sample, thanks!
EDIT: IDA couldn't find anything...

**Comment by char-ptr** [comment]
>  EDIT: IDA couldn't find anything...


Did you try both 3.4.4 and >3.4.4 versions?

**Comment by char-ptr** [comment]
Okay i think i have figured out the issue, it seems that the executable you used on was built with debug mode enabled, which messes up alot of my signatures. I'll make a patch shortly.

Thank you very much for helping me with this.

**Comment by char-ptr** [comment]
Hi, @polybiusproxy 

Sorry for the long delay, i decided to rewrite the code base cause i honestly just wasn't happy with it. From my testing, your issue should cease to exist (🥳). Please try out the new release (or build yourself) and tell me if it's resolved.

Thanks

**Comment by polybiusproxy** [comment]
Hey Luna!

Of course, I will try it once I'm free!
I will make another post once I try it.

Thanks!

**Comment by polybiusproxy** [comment]
Hey, I can confirm the tool now works as expected! 🎉 🥳

**Comment by char-ptr** [comment]
That's great to hear, I'll close this issue now. Thanks again for reporting this bug
