### ISSUE TITLE
Trouble knowing how to use this

### ISSUE THREAD

**Issue by EmZaid** [pozm/godot_key_extract#2]
I'm struggling to get this to work. I successfully can open and build it, but after it is built, I don't know what to do. I feel like I am missing something really basic. I can see the .dll (and other output files) but I am unsure how to use it to extract the key from the godot binary I am working with. Sorry in advance if this is a basic question.

**Comment by char-ptr** [comment]
The source should build it as a dll file, with the dll file you can use a tool like _extreme injector or a similar tool_ to inject the dll into the process. you will know if it's worked as it should create a console and spit out the key. 

You can find my tool of choice [here (extreme injector)](https://github.com/master131/ExtremeInjector)

**Comment by EmZaid** [comment]
Thank you. That was exactly what I needed. the injector worked perfectly!
