### ISSUE TITLE
[BUG] : Injecting the .dll does absolutely nothing

### ISSUE THREAD

**Issue by Oolks** [pozm/godot_key_extract#3]
As defined by the title

**Comment by char-ptr** [comment]
Hi thanks for the report, What dll injecting tool are you using? I personally would recommend extreme injector if you're not  already using it. 

I generally don't think there is anything wrong with the dll as one of the first things which i do in the dll is attach a console to the injected process, if you don't see that then i can only assume the injection went wrong. 

There may also be the slight chance of the game having some sort of anticheat which can detect such, but this is extremely unlikely.

**Comment by Oolks** [comment]
> Hi thanks for the report, What dll injecting tool are you using? I personally would recommend extreme injector if you're not already using it.
> 
> I generally don't think there is anything wrong with the dll as one of the first things which i do in the dll is attach a console to the injected process, if you don't see that then i can only assume the injection went wrong.
> 
> There may also be the slight chance of the game having some sort of anticheat which can detect such, but this is extremely unlikely.

Hi! I am using process hacker injector and also am using the release dll and didnt compile.I dont know how I can attach a console. Could you guide me?

**Comment by char-ptr** [comment]
The dll should automatically allocate and attach the console upon being injected, which is the strangest part about what's happening. i've just tried using process hacker and it injected and managed to find the key fine (using release dll). could you perhaps show a recording if possible, im really not too sure what could be causing this?

**Comment by Oolks** [comment]
> The dll should automatically allocate and attach the console upon being injected, which is the strangest part about what's happening. i've just tried using process hacker and it injected and managed to find the key fine (using release dll). could you perhaps show a recording if possible, im really not too sure what could be causing this?

Indeed! I will provide a video tomorrow! But the thing is, when I click on inject, nothing happens and using older versions kills the process

**Comment by Oolks** [comment]
> The dll should automatically allocate and attach the console upon being injected, which is the strangest part about what's happening. i've just tried using process hacker and it injected and managed to find the key fine (using release dll). could you perhaps show a recording if possible, im really not too sure what could be causing this?

https://www.youtube.com/watch?v=ORIXyminzpg here is the video also do you got discord?

**Comment by char-ptr** [comment]
Hmm I've watched the video and i'm even more confused now. Could you perhaps try using [extreme injector (click here)](https://github.com/master131/ExtremeInjector) just to try it? if that doesn't work we can try to resolve it on discord, my tag: `aixeria#9609`

**Comment by Oolks** [comment]
> Hmm I've watched the video and i'm even more confused now. Could you perhaps try using [extreme injector (click here)](https://github.com/master131/ExtremeInjector) just to try it? if that doesn't work we can try to resolve it on discord, my tag: `aixeria#9609`

sure

**Comment by char-ptr** [comment]
latest commit fixed the godot incompatibility
