### ISSUE TITLE
Hello, may I ask that I always fail to inject

### ISSUE THREAD

**Issue by Magic-KK** [pozm/godot_key_extract#4]
![E9NZKJ@OOV7PUQIT41Q2HVY](https://user-images.githubusercontent.com/20788521/218843189-09c4ff3c-fd04-4816-9fc0-3c9a199c4793.png)

godot version is 3.5.1

**Comment by char-ptr** [comment]
Hi, im unsure as to why you're experiencing issues when injecting. i have created a external version of this tool, i suggest you try to use that instead. you may find it at [pozm/gdke](https://github.com/pozm/gdke)

**Comment by Magic-KK** [comment]
> Hi, im unsure as to why you're experiencing issues when injecting. i have created a external version of this tool, i suggest you try to use that instead. you may find it at [pozm/gdke](https://github.com/pozm/gdke)

Thanks, I'll go back and try
